##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.29.2] date: [Thu Aug 09 13:00:50 CEST 2018]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = helloWorld


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
STemWin/App/BASIC_HelloWorld.c \
Core/Src/main.c \
Core/Src/stm32l4xx_it.c \
Core/Src/stm32l4xx_hal_msp.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma2d.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dsi.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gfxmmu.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_ltdc.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rng.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc_ex.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_fmc.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_sdmmc.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/BSP/Components/ft3x67/ft3x67.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/BSP/Components/mfxstm32l152/mfxstm32l152.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/BSP/STM32L4R9I-Discovery/stm32l4r9i_discovery.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/BSP/STM32L4R9I-Discovery/stm32l4r9i_discovery_io.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Middlewares/ST/STemWin/OS/GUI_X.c \
STemWin/Target/GUIConf.c \
STemWin/Target/LCDConf.c \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/system_stm32l4xx.c \
# ASM sources
ASM_SOURCES =  \
C:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates/gcc/startup_stm32l4r9xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L4R9xx \
-DUSE_STM32L4R9I_DISCOVERY \
-DUSE_IOEXPANDER \
-DBSP_LCD_COLOR_DEPTH_16_BPP \

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/STM32L4xx_HAL_Driver/Inc \
-IC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include \
-IC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/CMSIS/Include \
-ISTemWin/Target \
-IC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/BSP/STM32L4R9I-Discovery \
-IC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/BSP/Components/Common \
-IC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/BSP/Components/ft3x67 \
-IC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Drivers/BSP/Components/mfxstm32l152 \
-IC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Middlewares/ST/STemWin/inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = SW4STM32/STM32L4R9I-Discovery/STM32L4R9AIIx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys -l:STemWin540_CM4_GCC_ARGB.a
LIBDIR = -LC:/Users/erikr/STM32Cube/Repository/STM32Cube_FW_L4_V1.12.0/Middlewares/ST/STemWin/Lib
# LIBDIR = -L"C:\Users\erikr\STM32Cube\Repository\STM32Cube_FW_L4_V1.12.0\Middlewares\ST\STemWin\Lib"
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***