# Macro used to list all sub-directories
macro(nsfw_list_subdirs result PARENT_DIR)
  file(GLOB children RELATIVE ${PARENT_DIR} ${PARENT_DIR}/*)
  set(CHILD_LIST "")
  foreach(child ${children})
    if(IS_DIRECTORY ${PARENT_DIR}/${child})
      list(APPEND CHILD_LIST ${child})
    endif()
  endforeach()
  set(${result} ${CHILD_LIST})
endmacro()